# Generated by Django 4.0.5 on 2022-07-04 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('first_name', models.CharField(max_length=50, verbose_name='First name')),
                ('middle_name', models.CharField(max_length=50, verbose_name='Middle name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last name')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InsuranceCompany',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InsurancePolicy',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=100, unique=True, verbose_name='Number')),
                ('registration_date', models.DateTimeField(auto_now_add=True, verbose_name='Registration date')),
                ('start_date', models.DateTimeField(auto_now_add=True, verbose_name='Start date')),
                ('end_date', models.DateTimeField(verbose_name='End date')),
                ('insurance_sum', models.DecimalField(decimal_places=2, max_digits=15)),
                ('insurance_premium', models.DecimalField(decimal_places=2, max_digits=15)),
                ('description', models.TextField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('insurance_company', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='insurance_policies.insurancecompany')),
                ('policy_holder', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='policy_holder', to='insurance_policies.client')),
                ('policy_owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='policy_owner', to='insurance_policies.client')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='TypeOfInsurance',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='RiskTable',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('insurance_rate', models.DecimalField(decimal_places=4, max_digits=7)),
                ('insurance_premium', models.DecimalField(decimal_places=2, max_digits=15)),
                ('insurance_policy', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='insurance_policies', to='insurance_policies.insurancepolicy')),
                ('risk', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='risk', to='insurance_policies.risk')),
            ],
        ),
        migrations.CreateModel(
            name='PeriodOfInsurance',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateTimeField(auto_now_add=True, verbose_name='Start date')),
                ('end_date', models.DateTimeField(verbose_name='End date')),
                ('insurance_policy', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ins_policies', to='insurance_policies.insurancepolicy')),
            ],
        ),
        migrations.AddField(
            model_name='insurancepolicy',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='insurance_policies.product'),
        ),
        migrations.AddField(
            model_name='insurancepolicy',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='insurance_policies.region'),
        ),
        migrations.AddField(
            model_name='insurancepolicy',
            name='type_Of_insurance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='insurance_policies.typeofinsurance'),
        ),
    ]
