# Generated by Django 4.0.5 on 2022-07-05 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_policies', '0001_initial'),
    ]

    operations = [
    ]
